# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.destroy_all
Membership.destroy_all
Clubhouse.destroy_all
Post.destroy_all

puts 'CREATING CLUBHOUSES...'

30.times do |clubhouse_n|
  title = "TED talks: #{Faker::ProgrammingLanguage.name} ##{clubhouse_n}"

  clubhouse = Clubhouse.new(
    title:,
    description: [nil, "a description generated by seed for the cluubhouse #{title}:\n
      #{Faker::Lorem.paragraph_by_chars(number: 100, supplemental: false)}"].sample
  )

  puts 'created clubhouse' if clubhouse.save
end

puts '...CLUBHOUSES CREATED'

all_clubhouses = Clubhouse.all

i = 0
3.times do |_user_n|
  user = User.new(
    username: Faker::Internet.username(specifier: 3...20),
    email: Faker::Internet.email
  )

  until user.save
    user = User.new(
      username: Faker::Internet.username(specifier: 3...20),
      email: Faker::Internet.email
    )
  end

  (i...i + 10).each do |clubhouse_i|
    puts clubhouse_i
    Membership.create(user:, clubhouse: all_clubhouses[clubhouse_i], role: 'owner')
  end

  i += 10
end

i = 0
3.times do |_user_n|
  user = User.new(
    username: Faker::Internet.username(specifier: 3...20),
    email: Faker::Internet.email
  )

  until user.save
    user = User.new(
      username: Faker::Internet.username(specifier: 3...20),
      email: Faker::Internet.email
    )
  end

  (i...i + 2).each do |clubhouse_i|
    puts clubhouse_i
    Membership.create(user:, clubhouse: all_clubhouses[clubhouse_i], role: 'admin')
  end

  i += 10
end

clubhouse = Clubhouse.first
users = [*clubhouse.owners, *clubhouse.admins]
(10..30).to_a.sample.times do |_user_n|
  user = users.sample
  Post.create(
    user:,
    clubhouse:,
    content: Faker::Lorem.paragraph_by_chars(number: 500, supplemental: false)
  )
end

clubhouse = Clubhouse.second
users = [*clubhouse.owners, *clubhouse.admins]
(40..50).to_a.sample.times do |_user_n|
  user = users.sample
  Post.create(
    user:,
    clubhouse:,
    content: Faker::Lorem.paragraph_by_chars(number: 500, supplemental: false)
  )
end

post = Post.first
post_author = post.user
10.times do
  Comment.create(
    user: post_author,
    post:,
    content: Faker::Lorem.paragraph_by_chars(
      number: 100,
      supplemental: false
    )
  )
end

post = Post.second
post_author = post.user
10.times do
  Comment.create(
    user: post_author,
    post:,
    content: Faker::Lorem.paragraph_by_chars(
      number: 100,
      supplemental: false
    )
  )
end
